version: '3.6'
services:
  new-years-functions:
    container_name: new-years-functions
    image: 'haydenbr/new-years-functions:0.0.3'
    ports:
      - '3100:80'
    networks:
      - new-years-functions
networks:
  new-years-functions: null
